# Las Vegas Continuum of Care - Verified Resource Data
# Last Updated: January 25, 2026

COORDINATED_ENTRY_POINTS = [
    {
        "id": "courtyard-ce",
        "name": "The Courtyard Homeless Resource Center",
        "category": "coordinated_entry",
        "subcategory": "adults",
        "target_population": "Adults (Single/Couples)",
        "description": "The main hub for housing assessments and coordinated entry into the HMIS system. Open 24/7. This is where adults start their journey to long-term housing.",
        "address": "314 Foremaster Ln, Las Vegas, NV 89101",
        "phone": "(702) 229-6117",
        "hours": "24/7",
        "website": "https://lasvegasnevada.gov/residents/homeless-services",
        "services": ["Housing Assessment", "Coordinated Entry", "Safe Sleep", "Day Services", "Case Management"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1823, "lng": -115.1353},
        "notes": "Main hub for assessments. Start here for housing."
    },
    {
        "id": "catholic-charities-ce",
        "name": "Catholic Charities of Southern Nevada",
        "category": "coordinated_entry",
        "subcategory": "adults",
        "target_population": "Adults",
        "description": "Men's shelter and intake center. Provides coordinated entry assessments and emergency shelter for single adult men.",
        "address": "1511 Las Vegas Blvd N, Las Vegas, NV 89101",
        "phone": "(702) 385-2662",
        "hours": "Mon-Fri: 8am-4:30pm",
        "website": "https://catholiccharities.com",
        "services": ["Housing Assessment", "Coordinated Entry", "Men's Shelter", "Food Pantry", "Case Management"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1789, "lng": -115.1357},
        "notes": "Men's shelter & intake center"
    },
    {
        "id": "family-promise-ce",
        "name": "Family Promise of Las Vegas",
        "category": "coordinated_entry",
        "subcategory": "families",
        "target_population": "Families with Children",
        "description": "Focuses on keeping families together. Call first for coordinated entry assessment and family shelter services.",
        "address": "3110 E. Twain Ave, Las Vegas, NV 89121",
        "phone": "(702) 638-8806",
        "hours": "Mon-Fri: 9am-5pm (Call first)",
        "website": "https://familypromise.org",
        "services": ["Family Housing Assessment", "Coordinated Entry", "Family Shelter", "Case Management", "Child Services"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1283, "lng": -115.1181},
        "notes": "Call first. Keeps families together."
    },
    {
        "id": "help-sn-ce",
        "name": "HELP of Southern Nevada",
        "category": "coordinated_entry",
        "subcategory": "families_youth",
        "target_population": "Families / Youth",
        "description": "The main hub for social services & youth. Provides coordinated entry, emergency assistance, and comprehensive family services.",
        "address": "1640 E. Flamingo Rd, Las Vegas, NV 89119",
        "phone": "(702) 369-4357",
        "hours": "Mon-Fri: 8am-5pm",
        "website": "https://helpsonv.org",
        "services": ["Housing Assessment", "Coordinated Entry", "Youth Services", "Family Services", "Emergency Assistance", "Utility Help"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1152, "lng": -115.1253},
        "notes": "Main hub for social services & youth"
    },
    {
        "id": "nphy-ce",
        "name": "Nevada Partnership for Homeless Youth (NPHY)",
        "category": "coordinated_entry",
        "subcategory": "youth",
        "target_population": "Youth (12-24)",
        "description": "Safe space specifically for young people ages 12-24. Drop-in center with coordinated entry for youth housing programs.",
        "address": "4981 Shirley St, Las Vegas, NV 89119",
        "phone": "(702) 383-1332",
        "hours": "24/7 Crisis Line | Drop-In: Mon-Fri 9am-5pm",
        "website": "https://nphy.org",
        "services": ["Youth Housing Assessment", "Coordinated Entry", "Drop-In Center", "Crisis Support", "Education Help"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1047, "lng": -115.1522},
        "notes": "Safe space for young people 12-24"
    },
    {
        "id": "va-crrc-ce",
        "name": "VA Community Resource & Referral Center (CRRC)",
        "category": "coordinated_entry",
        "subcategory": "veterans",
        "target_population": "Veterans",
        "description": "The Community Resource & Referral Center for Veterans. One-stop shop for VA benefits, housing, and coordinated entry for veteran-specific programs like SSVF and HUD-VASH.",
        "address": "4461 E. Charleston Blvd, Las Vegas, NV 89104",
        "phone": "(702) 791-9077",
        "hours": "Mon-Fri: 7am-4pm",
        "website": "https://va.gov/homeless",
        "services": ["Veteran Housing Assessment", "Coordinated Entry", "SSVF", "HUD-VASH", "VA Benefits Help", "Employment"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1598, "lng": -115.0996},
        "notes": "Veterans only. SSVF & HUD-VASH access."
    }
]

EMERGENCY_SHELTERS = [
    {
        "id": "courtyard-shelter",
        "name": "The Courtyard Homeless Resource Center",
        "category": "shelter",
        "subcategory": "low_barrier",
        "target_population": "Adults",
        "description": "Low barrier, safe sleep facility. No sobriety requirements. The primary emergency shelter for single adults in Las Vegas.",
        "address": "314 Foremaster Ln, Las Vegas, NV 89101",
        "phone": "(702) 229-6117",
        "hours": "24/7",
        "website": "https://lasvegasnevada.gov/residents/homeless-services",
        "services": ["Emergency Shelter", "Safe Sleep", "Showers", "Meals", "Day Services", "Storage"],
        "is_coordinated_entry": True,
        "accepts_pets": False,
        "bed_tracking": True,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1823, "lng": -115.1353},
        "notes": "Low barrier shelter. No sobriety requirement."
    },
    {
        "id": "rescue-mission",
        "name": "Las Vegas Rescue Mission",
        "category": "shelter",
        "subcategory": "recovery",
        "target_population": "Adults",
        "description": "Recovery-focused emergency shelter with faith-based services. Offers long-term recovery programs alongside emergency beds.",
        "address": "480 W Bonanza Rd, Las Vegas, NV 89106",
        "phone": "(702) 382-1766",
        "hours": "24/7 | Dinner: 5pm daily",
        "website": "https://vegasrescue.org",
        "services": ["Emergency Shelter", "Recovery Program", "Meals", "Chapel Services", "Job Training"],
        "is_coordinated_entry": False,
        "accepts_pets": False,
        "bed_tracking": True,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1752, "lng": -115.1482},
        "notes": "Recovery focused. Faith-based services."
    },
    {
        "id": "shade-tree",
        "name": "The Shade Tree",
        "category": "shelter",
        "subcategory": "women_children",
        "target_population": "Women, Children, Pets",
        "description": "Nevada's largest shelter for women and children. CRITICAL: They allow pets! Safe haven for women fleeing domestic violence or experiencing homelessness.",
        "address": "1 W Owens Ave, Las Vegas, NV 89030",
        "phone": "(702) 385-0072",
        "hours": "24/7",
        "website": "https://theshadetree.org",
        "services": ["Women's Shelter", "Children's Programs", "Pet Friendly", "Domestic Violence Support", "Job Training"],
        "is_coordinated_entry": False,
        "accepts_pets": True,
        "bed_tracking": True,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1956, "lng": -115.1459},
        "notes": "ALLOWS PETS! Women & children only."
    },
    {
        "id": "safenest",
        "name": "SafeNest",
        "category": "shelter",
        "subcategory": "domestic_violence",
        "target_population": "Domestic Violence Survivors",
        "description": "Confidential domestic violence shelter. Location is hidden for safety. Call the 24/7 hotline for emergency shelter placement.",
        "address": "Confidential Location",
        "phone": "(702) 646-4981",
        "hours": "24/7 Hotline",
        "website": "https://safenest.org",
        "services": ["DV Emergency Shelter", "Crisis Counseling", "Legal Advocacy", "Safety Planning", "Children's Services"],
        "is_coordinated_entry": False,
        "accepts_pets": False,
        "bed_tracking": False,
        "verified_date": "2026-01-25",
        "coordinates": None,
        "notes": "CONFIDENTIAL LOCATION. Call hotline for help."
    },
    {
        "id": "shannon-west",
        "name": "Shannon West Homeless Youth Center",
        "category": "shelter",
        "subcategory": "youth",
        "target_population": "Youth 16-24",
        "description": "Safe shelter specifically for homeless youth ages 16-24. Part of HELP of Southern Nevada.",
        "address": "1650 E Flamingo Rd, Las Vegas, NV 89119",
        "phone": "(702) 369-4357",
        "hours": "24/7",
        "website": "https://helpsonv.org",
        "services": ["Youth Shelter", "Meals", "Education Support", "Life Skills", "Mental Health"],
        "is_coordinated_entry": False,
        "accepts_pets": False,
        "bed_tracking": True,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1152, "lng": -115.1253},
        "notes": "Youth ages 16-24 only"
    },
    {
        "id": "salvation-army-owens",
        "name": "Salvation Army (Owens Campus)",
        "category": "shelter",
        "subcategory": "general",
        "target_population": "Adults",
        "description": "Emergency shelter and rehabilitation programs for adults. Also offers meal services and seasonal assistance.",
        "address": "35 W Owens Ave, Las Vegas, NV 89030",
        "phone": "(702) 649-8240",
        "hours": "Shelter: 24/7 | Office: 9am-3pm",
        "website": "https://salvationarmysouthernnevada.org",
        "services": ["Emergency Shelter", "Rehabilitation", "Meals", "Holiday Assistance", "Utility Help"],
        "is_coordinated_entry": False,
        "accepts_pets": False,
        "bed_tracking": True,
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1959, "lng": -115.1467},
        "notes": "Also offers rehab programs"
    }
]

FOOD_RESOURCES = [
    {
        "id": "st-vincents",
        "name": "St. Vincent's Dining Room (Catholic Charities)",
        "category": "food",
        "subcategory": "hot_meal",
        "target_population": "Anyone",
        "description": "Free daily hot meal served every day. No questions asked, no ID required.",
        "address": "1501 Las Vegas Blvd N, Las Vegas, NV 89101",
        "phone": "(702) 385-2662",
        "hours": "Daily: 10am-11am",
        "website": "https://catholiccharities.com",
        "services": ["Hot Meal", "No ID Required"],
        "meal_times": "10:00 AM - 11:00 AM Daily",
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1789, "lng": -115.1357},
        "notes": "Free daily meal. No ID needed."
    },
    {
        "id": "rescue-mission-food",
        "name": "Las Vegas Rescue Mission",
        "category": "food",
        "subcategory": "hot_meal",
        "target_population": "Anyone",
        "description": "Free community dinner served daily at 5:00 PM. All are welcome.",
        "address": "480 W Bonanza Rd, Las Vegas, NV 89106",
        "phone": "(702) 382-1766",
        "hours": "Dinner: 5pm daily",
        "website": "https://vegasrescue.org",
        "services": ["Hot Dinner", "Community Meal"],
        "meal_times": "5:00 PM Daily",
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1752, "lng": -115.1482},
        "notes": "Free dinner at 5pm every day"
    },
    {
        "id": "city-mission",
        "name": "City Mission of Las Vegas",
        "category": "food",
        "subcategory": "food_pantry",
        "target_population": "Anyone",
        "description": "Food boxes and meals for those in need. Also provides clothing assistance.",
        "address": "3983 E Desert Inn Rd, Las Vegas, NV 89121",
        "phone": "(702) 431-9966",
        "hours": "Mon-Fri: 9am-3pm",
        "website": "https://citymissionlv.org",
        "services": ["Food Boxes", "Meals", "Clothing"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1273, "lng": -115.0923},
        "notes": "Food boxes and clothing"
    },
    {
        "id": "just-one-project",
        "name": "Just One Project",
        "category": "food",
        "subcategory": "mobile_pantry",
        "target_population": "Anyone",
        "description": "Massive mobile food pantry with pop-up locations throughout Las Vegas. Check their website for current distribution schedule.",
        "address": "Various Pop-Up Locations",
        "phone": "(702) 462-2253",
        "hours": "Check website for schedule",
        "website": "https://justoneproject.org",
        "services": ["Mobile Food Pantry", "Pop-Up Distributions", "Bulk Food"],
        "verified_date": "2026-01-25",
        "coordinates": None,
        "notes": "Mobile pantry - check website for locations"
    },
    {
        "id": "three-square",
        "name": "Three Square Food Bank",
        "category": "food",
        "subcategory": "food_bank",
        "target_population": "Anyone",
        "description": "Southern Nevada's food bank distributor. Find food pantries, mobile distributions, and SNAP enrollment help.",
        "address": "4190 N Pecos Rd, Las Vegas, NV 89115",
        "phone": "(702) 644-3663",
        "hours": "Distribution varies by location",
        "website": "https://threesquare.org/find-food",
        "services": ["Food Pantry Network", "Mobile Distributions", "Senior Programs", "SNAP Help"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.2150, "lng": -115.1019},
        "notes": "Use their 'Find Food' map for pantry locations"
    }
]

MEDICAL_RESOURCES = [
    {
        "id": "nevada-health-outreach",
        "name": "Nevada Health Centers - Las Vegas Outreach Clinic",
        "category": "medical",
        "subcategory": "healthcare_homeless",
        "target_population": "Anyone",
        "description": "Healthcare for the Homeless program. Primary care, dental, and behavioral health for unhoused individuals.",
        "address": "47 W Owens Ave, Las Vegas, NV 89030",
        "phone": "(702) 214-5948",
        "hours": "Mon-Fri: 8am-5pm",
        "website": "https://nvhealthcenters.org",
        "services": ["Primary Care", "Dental", "Behavioral Health", "Prescription Help", "Healthcare for Homeless"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1959, "lng": -115.1467},
        "notes": "Healthcare for the Homeless clinic"
    },
    {
        "id": "nevada-health-mobile",
        "name": "Nevada Health Centers - Mobile Medical Van",
        "category": "medical",
        "subcategory": "mobile_health",
        "target_population": "Anyone",
        "description": "Mobile medical van that travels to The Courtyard and other shelter locations. Brings healthcare directly to the streets.",
        "address": "Mobile - Visits The Courtyard & Shelters",
        "phone": "(702) 214-5948",
        "hours": "Check for schedule",
        "website": "https://nvhealthcenters.org",
        "services": ["Mobile Primary Care", "Vaccinations", "Health Screenings"],
        "verified_date": "2026-01-25",
        "coordinates": None,
        "notes": "Mobile van visits Courtyard & shelters"
    },
    {
        "id": "first-person-care",
        "name": "First Person Care Clinic",
        "category": "medical",
        "subcategory": "trauma_informed",
        "target_population": "Anyone",
        "description": "Trauma-informed healthcare clinic. Specializes in serving vulnerable populations with dignity and respect.",
        "address": "1200 S 4th St, Las Vegas, NV 89104",
        "phone": "(702) 366-1640",
        "hours": "Mon-Fri: 8am-5pm",
        "website": "https://firstpersoncare.org",
        "services": ["Trauma-Informed Care", "Primary Care", "Mental Health", "Substance Use Support"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1598, "lng": -115.1496},
        "notes": "Trauma-informed care specialists"
    },
    {
        "id": "snhd-sexual-health",
        "name": "Southern Nevada Health District - Sexual Health Clinic",
        "category": "medical",
        "subcategory": "sexual_health",
        "target_population": "Anyone",
        "description": "Free and low-cost STI testing and treatment, HIV testing, PrEP, and reproductive health services.",
        "address": "280 S Decatur Blvd, Las Vegas, NV 89107",
        "phone": "(702) 759-0702",
        "hours": "Mon-Fri: 8am-4pm",
        "website": "https://snhd.info",
        "services": ["STI Testing", "HIV Testing", "PrEP", "Treatment", "Family Planning"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1650, "lng": -115.2073},
        "notes": "Free/low-cost STI & HIV services"
    },
    {
        "id": "mojave-mental-health",
        "name": "Mojave Mental Health",
        "category": "medical",
        "subcategory": "mental_health",
        "target_population": "Anyone",
        "description": "Crisis intervention and ongoing mental health services. Multiple locations throughout Clark County.",
        "address": "Various Locations",
        "phone": "(702) 968-4357",
        "hours": "Crisis Line: 24/7",
        "website": "https://mojavecouncil.org",
        "services": ["Crisis Intervention", "Mental Health Counseling", "Psychiatric Services", "Case Management"],
        "verified_date": "2026-01-25",
        "coordinates": None,
        "notes": "24/7 mental health crisis line"
    }
]

LEGAL_RESOURCES = [
    {
        "id": "nevada-homeless-alliance",
        "name": "Nevada Homeless Alliance",
        "category": "legal",
        "subcategory": "id_services",
        "target_population": "Anyone",
        "description": "Runs 'Project Homeless Connect' events with ID replacement, warrant help, and resource connection. Also provides advocacy.",
        "address": "1535 W Warm Springs Rd, Henderson, NV 89014",
        "phone": "(702) 455-4906",
        "hours": "Mon-Fri: 9am-5pm | Events vary",
        "website": "https://nevadahomelessalliance.org",
        "services": ["Project Homeless Connect", "ID Replacement", "Warrant Help", "Advocacy", "Resource Navigation"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.0326, "lng": -115.0803},
        "notes": "Runs ID & warrant events"
    },
    {
        "id": "legal-aid-center",
        "name": "Legal Aid Center of Southern Nevada",
        "category": "legal",
        "subcategory": "legal_services",
        "target_population": "Low-Income",
        "description": "Free civil legal services including eviction defense, consumer protection, family law, and immigration help.",
        "address": "725 E Charleston Blvd, Las Vegas, NV 89104",
        "phone": "(702) 386-1070",
        "hours": "Mon-Fri: 8am-5pm",
        "website": "https://lacsn.org",
        "services": ["Eviction Defense", "Consumer Protection", "Family Law", "Immigration", "Record Sealing"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1598, "lng": -115.1345},
        "notes": "Free legal help for low-income"
    },
    {
        "id": "silver-state-fair-housing",
        "name": "Silver State Fair Housing Council",
        "category": "legal",
        "subcategory": "housing_rights",
        "target_population": "Anyone",
        "description": "Help with housing discrimination complaints, fair housing education, and tenant rights.",
        "address": "1600 E Desert Inn Rd #103, Las Vegas, NV 89109",
        "phone": "(702) 733-1799",
        "hours": "Mon-Fri: 9am-5pm",
        "website": "https://silverstatehousing.org",
        "services": ["Housing Discrimination Help", "Fair Housing Education", "Tenant Rights", "Complaint Filing"],
        "verified_date": "2026-01-25",
        "coordinates": {"lat": 36.1273, "lng": -115.1373},
        "notes": "Housing discrimination help"
    }
]

# Combine all resources
ALL_RESOURCES = (
    COORDINATED_ENTRY_POINTS + 
    EMERGENCY_SHELTERS + 
    FOOD_RESOURCES + 
    MEDICAL_RESOURCES + 
    LEGAL_RESOURCES
)
